language: java
dist: trusty
os: linux
git:
  depth: 1
cache:
  directories:
    - $HOME/.m2
install: true
env:
  global:
    - secure: "MtoN2aezAyjNoVbQAnCaYfkXFyd5zYLoOCEQWkU6DQAGgeiPXWSDf6ZEBJsyFtZoet4cMMmhp47eznVkJs99chG1Ky3bLGNN99h7yQp8SW0XMlfyy+RsGgA+zGmZzPnRtyM98h+D1FIW0z65JByjrzXNS520ErE2MTJ7x6Xrx1A="
    - secure: "fM+VfobzmOtcjcQcVdG60LWNwfiN+jZxAq5le69pHhrGImGAWlurWP8iOZcTUZqCpkmia0fca+YVODaVscM1t+DztnnrVVkiz9x/wFaKKeZkR1NyY94HtL0DxMk+iX1KZXR6nJdP0fD5mQjAxJkPM5hO3AQAiyvLbhI2sGsiNQY="
    - secure: "RL7ewIRj4+fjM/X126xRs1m+ji3KIR4evgqBCxTOqkN6+9nNQnaPMW/ZukNnpvwyqJWTUw52hpPRVhXjnuJXoniG02/gWSy3SwH/Uk9QflciyfXYUONxWdWUBVctzyQzAfr8xgyDHr6nCckSVHbU+jeDPDX5/1Y6UAlQ+UbbwW8="
    - secure: "OlWvcGoTiQhq1PH2+4hM0A43AUGqTn/ydEaIx7Ht9w3QcOoryjYq77GiTwZpihMuR4xPb2krFwE4dVwrxv/VqgF7cVP83k/Vacwms1eM2xYRDTFkPea7M6YZxzOQiQXhZTO9UQ4wbB6pTrTOKnFxE9luBFhmAoDZ5i9jPIPbLmY="
    - secure: "XjfHWxZ58JpJFDDTRy/BXO/BG3+lpePWV1JtSh75GYXGMWiMeueEnZi7VWY7fkNb4wCrGrgLDZP4EaGJGeJDfnphTBOEWBeJZ+RhY/E6HbmxVN4EAp9tg91vAl1hFiv2dnRxiYrTXhZzPnfR/rsFrpy7lvjN6+Suq5ZmYrKcA7U="
jobs:
  include:
    - jdk: openjdk7
    - jdk: openjdk8
    - jdk: openjdk9
      after_success:
        - test $TRAVIS_BRANCH = "main" && test $TRAVIS_PULL_REQUEST = "false" && 
          openssl aes-256-cbc -pass pass:$ENCRYPTION_KEY -in .travis/pubring.asc.enc -out ./pubring.asc -d &&
          openssl aes-256-cbc -pass pass:$ENCRYPTION_KEY -in .travis/secring.asc.enc -out ./secring.asc -d &&
          ./mvnw clean deploy --settings .travis/settings.xml -Ddeployment -Dmaven.test.skip=true &&
          ./mvnw clean deploy --settings .travis/settings.xml -Ddeployment -Dgwt   -Dmaven.test.skip=true -f pom-gwt.xml  &&
          ./mvnw clean deploy --settings .travis/settings.xml -Ddeployment -Djdk3  -Dmaven.test.skip=true -f pom-jdk3.xml &&
          ./mvnw clean deploy --settings .travis/settings.xml -Ddeployment -Djdk8  -Dmaven.test.skip=true -f pom-jdk8.xml &&
          ./mvnw clean deploy --settings .travis/settings.xml -Ddeployment -Dgraal -Dmaven.test.skip=true -f pom-graal.xml
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: openjdk12
    - jdk: openjdk13
    - jdk: openjdk14
    - jdk: openjdk15
    - jdk: openjdk16
    - jdk: openjdk-ea
script: 
  - ./mvnw clean package -Dmaven.javadoc.skip=false
  - sed 's;<artifactId>joml</artifactId>;<artifactId>joml-gwt</artifactId>;'  pom.xml > pom-gwt.xml  && ./mvnw clean package -Dmaven.javadoc.skip=false -Dgwt  -f pom-gwt.xml
  - sed 's;<artifactId>joml</artifactId>;<artifactId>joml-jdk3</artifactId>;' pom.xml > pom-jdk3.xml && ./mvnw clean package -Dmaven.javadoc.skip=false -Djdk3 -f pom-jdk3.xml
  - sed 's;<artifactId>joml</artifactId>;<artifactId>joml-jdk8</artifactId>;' pom.xml > pom-jdk8.xml && ./mvnw clean package -Dmaven.javadoc.skip=false -Djdk8 -f pom-jdk8.xml
  - sed 's;<artifactId>joml</artifactId>;<artifactId>joml-graal</artifactId>;' pom.xml > pom-graal.xml && ./mvnw clean package -Dmaven.javadoc.skip=false -Dgraal -f pom-graal.xml
